=== simplecommand/simple-command-tools/generatorexample/src/main/resources/META-INF/classes.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="classes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="class" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="package"/>
              <xs:element type="xs:string" name="classcomment"/>
              <xs:element type="xs:string" name="author"/>
              <xs:element type="xs:string" name="version"/>
              <xs:element type="xs:string" name="template"/>
              <xs:element name="instancevariables">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="instancevariable" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="id" use="required"/>
                            <xs:attribute type="xs:string" name="type" use="required"/>
                            <xs:attribute type="xs:string" name="scope" use="required"/>
                            <xs:attribute type="xs:string" name="cardinality" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="identifier" use="required"/>
            <xs:attribute type="xs:string" name="extends" use="optional"/>
            <xs:attribute type="xs:string" name="implements" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== simplecommand/simple-command-tools/generatorexample/src/main/resources/class.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="classes.xsd">

    <class identifier="Person">
        <package>gen.org.mwolff.generatorexamples.entity</package>
        <classcomment>Structure of a Person class.</classcomment>
        <author>Manfred Wolff</author>
        <version>1.0.0</version>
        <template>class-template.vm</template>
        <instancevariables>
            <instancevariable id="name" type="String" scope="private"/>
            <instancevariable id="prename" type="String" scope="private"/>
            <instancevariable id="adress" type="Adress" scope="private" cardinality="one-many"/>
        </instancevariables>
    </class>

    <class identifier="Adress">
        <package>gen.org.mwolff.generatorexamples.entity</package>
        <classcomment>Structure of a Address class.</classcomment>
        <author>Manfred Wolff</author>
        <version>1.0.0</version>
        <template>class-template.vm</template>
        <instancevariables>
            <instancevariable id="zip" type="String" scope="private"/>
            <instancevariable id="street" type="String" scope="private"/>
            <instancevariable id="city" type="String" scope="private"/>
        </instancevariables>
    </class>
</classes>

=== simplecommand/simple-command-tools/generator/src/test/resources/class2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="classes.xsd">

    <class identifier="GeneratedClassStructure">
        <package>gen.org.mwolff.generator.commands</package>
        <classcomment>Structure of a class to generate.</classcomment>
        <author>generator 0.0.2</author>
        <version>1.0.0</version>
        <template>class-template.vm</template>
        <instancevariables>
            <instancevariable id="identifier" type="String" scope="private"/>
            <instancevariable id="extendsString" type="String" scope="private"/>
            <instancevariable id="implementsString" type="String" scope="private"/>
            <instancevariable id="classComment" type="String" scope="private"/>
            <instancevariable id="packageString" type="String" scope="private"/>
            <instancevariable id="author" type="String" scope="private"/>
            <instancevariable id="version" type="String" scope="private"/>
            <instancevariable id="imports" type="String" scope="private" cardinality="one-many"/>
            <instancevariable id="instanceVariables" type="GeneratedInstanceVariable" scope="protected" cardinality="one-many"/>
        </instancevariables>
    </class>

    <class identifier="GeneratedInstanceVariable">
        <package>gen.org.mwolff.generator.commands</package>
        <classcomment>Structure of a instancevariable of a class.</classcomment>
        <author>generator 0.0.2</author>
        <version>1.0.0</version>
        <template>class-template.vm</template>
        <instancevariables>
            <instancevariable id="modifier" type="String" scope="private"/>
            <instancevariable id="type" type="String" scope="private"/>
            <instancevariable id="identifier" type="String" scope="private"/>
            <instancevariable id="cardinality" type="String" scope="private"/>
        </instancevariables>
    </class>
</classes>
